[package]
name = "syntect"
description = "library for high quality syntax highlighting and code intelligence using Sublime Text's grammars"
documentation = "http://thume.ca/rustdoc/syntect/syntect/"
repository = "https://github.com/trishume/syntect"
keywords = ["syntax", "highlighting", "highlighter", "colouring", "parsing"]
readme = "Readme.md"
license = "MIT"
version = "1.2.0"
authors = ["Tristan Hume <tristan@thume.ca>"]
exclude = [
    "testdata/*",
]

[dependencies]
yaml-rust = "0.3.5"
onig = "1.2.0"
walkdir = "^1.0"
regex-syntax = "^0.4"
lazy_static = "^0.2"
bitflags = "^0.8"
plist = "0.1.1"
rustc-serialize = "^0.3"
bincode = "0.6"
flate2 = "^0.2"
fnv = "^1.0"

[dev-dependencies]
regex = "0.2.1"

[features]
static-onig = ["onig/static-libonig"]
assets = []
html = ["assets"]
default = ["assets", "html"]

# [profile.release]
# debug = true
