[package]
name = "syntect"
description = "library for high quality syntax highlighting and code intelligence using Sublime Text's grammars"
documentation = "https://docs.rs/syntect"
repository = "https://github.com/trishume/syntect"
keywords = ["syntax", "highlighting", "highlighter", "colouring", "parsing"]
categories = ["parser-implementations", "parsing", "text-processing"]
readme = "Readme.md"
license = "MIT"
version = "2.0.0" # remember to update html_root_url
authors = ["Tristan Hume <tristan@thume.ca>"]
exclude = [
    "testdata/*",
]

[dependencies]
yaml-rust = { version = "0.4", optional = true }
#onig = { version = "3.0", optional = true }
walkdir = "2.0"
regex-syntax = { version = "0.4", optional = true }
lazy_static = "1.0"
bitflags = "1.0"
plist = "0.2"
bincode = { version = "0.9", optional = true }
flate2 = { version = "1.0", optional = true }
libflate = { version = "0.1.8", optional = true }
fnv = { version = "1.0", optional = true }
regex = "*"
fancy-regex = { git = "https://github.com/robinst/fancy-regex.git", branch = "fix-negative-lookaround-matching" }
serde = { version = "1.0", features = ["rc"] }
serde_derive = "1.0"
serde_json = "1.0"

[dev-dependencies]
rayon = "0.9.0"
getopts = "0.2"
pretty_assertions = "0.4.0"

[features]

# If you enable two dump loading features or two creation features the build
# will fail, choose one of each. If you are using both creation and loading,
# your binary will be smaller if you choose the same one for each.

# Pure Rust dump loading, slower than regular `dump-load`
dump-load-rs = ["libflate", "bincode"]
# Dump loading using flate2, which depends on the miniz C library.
dump-load = ["flate2", "bincode"]
# Dump creation using flate2, which depends on the miniz C library.
dump-create = ["flate2", "bincode"]
# Pure Rust dump creation, worse compressor so produces larger dumps than dump-create
dump-create-rs = ["libflate", "bincode"]

#parsing = ["onig", "regex-syntax", "fnv"]
parsing = ["regex-syntax", "fnv"]
# The `assets` feature enables inclusion of the default theme and syntax packages.
# For `assets` to do anything, it requires one of `dump-load-rs` or `dump-load` to be set.
assets = []
html = ["parsing", "assets"]
yaml-load = ["yaml-rust", "parsing"]
default = ["parsing", "assets", "html", "yaml-load", "dump-load", "dump-create"]

# [profile.release]
# debug = true
